### ISSUE TITLE
ModuleNotFoundError: No module named 'mot_3d'

### ISSUE THREAD

**Issue by enesdorukadastec** [darrenjkt/MS3D#11]
Traceback (most recent call last):
  File "generate_tracks.py", line 16, in <module>
    from pcdet.utils import ms3d_utils
  File "/home/adastec/anaconda3/envs/ms3d/lib/python3.8/site-packages/pcdet-0.6.0+df3d0fa-py3.8-linux-x86_64.egg/pcdet/utils/ms3d_utils.py", line 7, in <module>
    from pcdet.utils.tracker_utils import get_frame_track_boxes, get_motion_state, delete_tracks
  File "/home/adastec/anaconda3/envs/ms3d/lib/python3.8/site-packages/pcdet-0.6.0+df3d0fa-py3.8-linux-x86_64.egg/pcdet/utils/tracker_utils.py", line 4, in <module>
    from mot_3d.frame_data import FrameData
ModuleNotFoundError: No module named 'mot_3d'
Traceback (most recent call last):
  File "generate_tracks.py", line 16, in <module>
    from pcdet.utils import ms3d_utils
  File "/home/adastec/anaconda3/envs/ms3d/lib/python3.8/site-packages/pcdet-0.6.0+df3d0fa-py3.8-linux-x86_64.egg/pcdet/utils/ms3d_utils.py", line 7, in <module>
    from pcdet.utils.tracker_utils import get_frame_track_boxes, get_motion_state, delete_tracks
  File "/home/adastec/anaconda3/envs/ms3d/lib/python3.8/site-packages/pcdet-0.6.0+df3d0fa-py3.8-linux-x86_64.egg/pcdet/utils/tracker_utils.py", line 4, in <module>
    from mot_3d.frame_data import FrameData
ModuleNotFoundError: No module named 'mot_3d'
Traceback (most recent call last):
  File "generate_tracks.py", line 16, in <module>
    from pcdet.utils import ms3d_utils
  File "/home/adastec/anaconda3/envs/ms3d/lib/python3.8/site-packages/pcdet-0.6.0+df3d0fa-py3.8-linux-x86_64.egg/pcdet/utils/ms3d_utils.py", line 7, in <module>
    from pcdet.utils.tracker_utils import get_frame_track_boxes, get_motion_state, delete_tracks
  File "/home/adastec/anaconda3/envs/ms3d/lib/python3.8/site-packages/pcdet-0.6.0+df3d0fa-py3.8-linux-x86_64.egg/pcdet/utils/tracker_utils.py", line 4, in <module>
    from mot_3d.frame_data import FrameData
ModuleNotFoundError: No module named 'mot_3d'
Traceback (most recent call last):
  File "temporal_refinement.py", line 12, in <module>
    from pcdet.utils import ms3d_utils
  File "/home/adastec/anaconda3/envs/ms3d/lib/python3.8/site-packages/pcdet-0.6.0+df3d0fa-py3.8-linux-x86_64.egg/pcdet/utils/ms3d_utils.py", line 7, in <module>
    from pcdet.utils.tracker_utils import get_frame_track_boxes, get_motion_state, delete_tracks
  File "/home/adastec/anaconda3/envs/ms3d/lib/python3.8/site-packages/pcdet-0.6.0+df3d0fa-py3.8-linux-x86_64.egg/pcdet/utils/tracker_utils.py", line 4, in <module>
    from mot_3d.frame_data import FrameData
ModuleNotFoundError: No module named 'mot_3d'

**Comment by darrenjkt** [comment]
Did you follow this line in INSTALL.md to install the tracker module? 

```
cd tracker && pip install -e . --user
```

**Comment by enesdorukadastec** [comment]
> Did you follow this line in our installation at docs/INSTALL.md to install the tracker module?
> 
> ```
> cd tracker && pip install -e . --user
> ```

python setup.py develop
cd tracker && pip install -e . --user

it worked, thanks a lot
