### ISSUE TITLE
Channel size mismatch in generate_ensemble_preds.sh

### ISSUE THREAD

**Issue by TimoRST** [darrenjkt/MS3D#19]
Hi!
I'm currently trying to use your project to annotate a custom dataset.
I've got to the point where I can call "bash cfgs/target_custom/label_generation/round1/scripts/generate_ensemble_preds.sh" and it actually executes until calling the models.

I've downloaded two models from your table:
Lyft: PV-RCNN++ (Anchor)
nuScenes: PV-RCNN++ (Anchor)

I've copied those files to MS3D/model_zoo/lyft_pretrained and /nuscenes_pretrained, respectively.
I copied the config files (to which the table also links) from MS3D/tools/cfgs/lyft_models and /nusenes_models, respectively.

Here, I noticed that in your demo and in the original .sh-Files the yaml-Files have more specific names.

I modified generate_ensemble_preds.sh to:
```
#!/bin/bash

# We set sweeps based on the assumption that your lidar data is at 10Hz
bash /MS3D/tools/cfgs/target_custom/label_generation/round1/scripts/pretrained/lyft_pt_dets_vx_a.sh
bash /MS3D/tools/cfgs/target_custom/label_generation/round1/scripts/pretrained/nusc_pt_dets_vx_a.sh
```
and 
lyft_pt_dets_vx_a.sh to:
```
#!/bin/bash
python test.py --cfg_file ../model_zoo/lyft_pretrained/cfgs/uda_pv_rcnn_plusplus_resnet_anchorhead.yaml \
                --ckpt ../model_zoo/lyft_pretrained/lyft_uda_pv_rcnn_plusplus_resnet_anchorhead_1xyz_allcls.pth \
                --eval_tag lyft3xyzt_custom4xyzt_rwf_rwr \
                --target_dataset custom --sweeps 1 --batch_size 8 --use_tta 3 \
                --set DATA_CONFIG_TAR.DATA_SPLIT.test train MODEL.POST_PROCESSING.EVAL_METRIC none
```
and nusc_pt_dets_vx_a.sh to:
```
#!/bin/bash
python test.py --cfg_file ../model_zoo/nuscenes_pretrained/cfgs/uda_pv_rcnn_plusplus_resnet_anchorhead.yaml \
                --ckpt ../model_zoo/nuscenes_pretrained/nuscenes_uda_pv_rcnn_plusplus_resnet_anchorhead_10xyzt_allcls.pth \
                --eval_tag nusc10xyzt_custom4xyzt_rwf_rwr \
                --target_dataset custom --sweeps 4 --batch_size 8 --use_tta 3 \
                --set DATA_CONFIG_TAR.DATA_SPLIT.test train MODEL.POST_PROCESSING.EVAL_METRIC none
```

If I now run generate_ensemble_preds.sh it is able to load the dataset (correct number of samples is shown) and it loads the checkpoint to GPU successfully.

When passing the first point cloud through the network, I get the following error:

```
2023-12-12 13:14:28,996   INFO  cfg.TAG: uda_pv_rcnn_plusplus_resnet_anchorhead
2023-12-12 13:14:28,996   INFO  cfg.EXP_GROUP_PATH: model_zoo/nuscenes_pretrained/cfgs
2023-12-12 13:14:28,996   INFO  Loading CustomDataset dataset
2023-12-12 13:14:28,997   INFO  Total samples for CustomDataset dataset: 80
2023-12-12 13:14:30,855   INFO  ==> Loading parameters from checkpoint ../model_zoo/nuscenes_pretrained/nuscenes_uda_pv_rcnn_plusplus_resnet_anchorhead_10xyzt_allcls.pth to GPU
2023-12-12 13:14:30,917   INFO  ==> Checkpoint trained from version: pcdet+0.6.0+
2023-12-12 13:14:30,937   INFO  ==> Done (loaded 461/461)
2023-12-12 13:14:30,952   INFO  *************** EPOCH 10 EVALUATION *****************
eval:   0%|                                                                                                                                                                          | 0/10 [00:00<?, ?it/s]Traceback (most recent call last):
  File "test.py", line 229, in <module>
    main()
  File "test.py", line 225, in main
    eval_single_ckpt(model, test_loader, args, eval_output_dir, logger, epoch_id, dist_test=dist_test)
  File "test.py", line 77, in eval_single_ckpt
    result_dir=eval_output_dir
  File "/MS3D/tools/eval_utils/eval_utils.py", line 66, in eval_one_epoch
    pred_dicts, ret_dict = model(batch_dict)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "../pcdet/models/detectors/pv_rcnn_plusplus.py", line 13, in forward
    batch_dict = self.backbone_2d(batch_dict)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "../pcdet/models/backbones_2d/base_bev_backbone.py", line 93, in forward
    x = self.blocks[i](x)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/container.py", line 119, in forward
    input = module(input)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/conv.py", line 399, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/conv.py", line 396, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Given groups=1, weight of size [128, 256, 3, 3], expected input[8, 896, 190, 190] to have 256 channels, but got 896 channels instead
```

I think this might be due to some mismatch between checkpoint and config file. As it is not the first layer, I assume that everything is fine with the point cloud.

Is this error related to a wrong config file and where do I find the correct ones?

Thank you very much!

**Comment by darrenjkt** [comment]
Could you show me the config file that you used for loading the nuscenes uda_pv_rcnn_plusplus_resnet_anchorhead.yaml model?

**Comment by TimoRST** [comment]
Thanks for your quick response!
Sure.
The link in the table redirects to: MS3D/tools/cfgs/nuscenes_models/uda_pv_rcnn_plusplus_resnet_anchorhead.yaml
And this is the config file I used.
Here is a copy of my local config file content, which should be an exact copy of the one in your repo.

```
CLASS_NAMES: ['car','truck','bus','motorcycle','bicycle','pedestrian']

DATA_CONFIG:
    _BASE_CONFIG_: cfgs/dataset_configs/nuscenes_dataset_da.yaml    
    MAX_SWEEPS: 10
    POINT_FEATURE_ENCODING: {
        encoding_type: absolute_coordinates_encoding,
        used_feature_list: ['x', 'y', 'z','timestamp'],
        src_feature_list: ['x', 'y', 'z','intensity','timestamp'],
    }

MODEL:
    NAME: PVRCNNPlusPlus

    VFE:
        NAME: MeanVFE

    BACKBONE_3D:
        NAME: VoxelResBackBone8x

    MAP_TO_BEV:
        NAME: HeightCompression
        NUM_BEV_FEATURES: 256

    BACKBONE_2D:
        NAME: BaseBEVBackbone

        LAYER_NUMS: [5, 5]
        LAYER_STRIDES: [1, 2]
        NUM_FILTERS: [128, 256]
        UPSAMPLE_STRIDES: [1, 2]
        NUM_UPSAMPLE_FILTERS: [256, 256]

    DENSE_HEAD:
        NAME: AnchorHeadSingle
        CLASS_AGNOSTIC: False

        USE_DIRECTION_CLASSIFIER: True
        DIR_OFFSET: 0.78539
        DIR_LIMIT_OFFSET: 0.0
        NUM_DIR_BINS: 2

        ANCHOR_GENERATOR_CONFIG: [
            {
                'class_name': car,
                'anchor_sizes': [[4.63, 1.97, 1.74]],
                'anchor_rotations': [0, 1.57],
                'anchor_bottom_heights': [0],
                'align_center': False,
                'feature_map_stride': 8,
                'matched_threshold': 0.6,
                'unmatched_threshold': 0.45
            },
            {
                'class_name': truck,
                'anchor_sizes': [[6.93, 2.51, 2.84]],
                'anchor_rotations': [0, 1.57],
                'anchor_bottom_heights': [0],
                'align_center': False,
                'feature_map_stride': 8,
                'matched_threshold': 0.55,
                'unmatched_threshold': 0.4
            },
            {
                'class_name': bus,
                'anchor_sizes': [[10.5, 2.94, 3.47]],
                'anchor_rotations': [0, 1.57],
                'anchor_bottom_heights': [0],
                'align_center': False,
                'feature_map_stride': 8,
                'matched_threshold': 0.55,
                'unmatched_threshold': 0.4
            },
            {
                'class_name': motorcycle,
                'anchor_sizes': [[2.11, 0.77, 1.47]],
                'anchor_rotations': [0, 1.57],
                'anchor_bottom_heights': [0],
                'align_center': False,
                'feature_map_stride': 8,
                'matched_threshold': 0.5,
                'unmatched_threshold': 0.3
            },
            {
                'class_name': bicycle,
                'anchor_sizes': [[1.70, 0.60, 1.28]],
                'anchor_rotations': [0, 1.57],
                'anchor_bottom_heights': [0],
                'align_center': False,
                'feature_map_stride': 8,
                'matched_threshold': 0.5,
                'unmatched_threshold': 0.35
            },
            {
                'class_name': pedestrian,
                'anchor_sizes': [[0.73, 0.67, 1.77]],
                'anchor_rotations': [0, 1.57],
                'anchor_bottom_heights': [0],
                'align_center': False,
                'feature_map_stride': 8,
                'matched_threshold': 0.6,
                'unmatched_threshold': 0.4
            }
        ]

        TARGET_ASSIGNER_CONFIG:
            NAME: AxisAlignedTargetAssigner
            POS_FRACTION: -1.0
            SAMPLE_SIZE: 512
            NORM_BY_NUM_EXAMPLES: False
            MATCH_HEIGHT: False
            BOX_CODER: ResidualCoder

        LOSS_CONFIG:
            LOSS_WEIGHTS: {
                'cls_weight': 1.0,
                'loc_weight': 0.25,
                'dir_weight': 0.2,
                'code_weights': [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
            }

    PFE:
        NAME: VoxelSetAbstraction
        POINT_SOURCE: raw_points
        NUM_KEYPOINTS: 4096
        NUM_OUTPUT_FEATURES: 90
        SAMPLE_METHOD: SPC
        SPC_SAMPLING:
            NUM_SECTORS: 6
            SAMPLE_RADIUS_WITH_ROI: 1.6

        FEATURES_SOURCE: ['bev', 'x_conv3', 'x_conv4', 'raw_points']
        SA_LAYER:
            raw_points:
                NAME: VectorPoolAggregationModuleMSG
                NUM_GROUPS: 2
                LOCAL_AGGREGATION_TYPE: local_interpolation
                NUM_REDUCED_CHANNELS: 1
                NUM_CHANNELS_OF_LOCAL_AGGREGATION: 32
                MSG_POST_MLPS: [ 32 ]
                FILTER_NEIGHBOR_WITH_ROI: True
                RADIUS_OF_NEIGHBOR_WITH_ROI: 2.4

                GROUP_CFG_0:
                    NUM_LOCAL_VOXEL: [ 2, 2, 2 ]
                    MAX_NEIGHBOR_DISTANCE: 0.2
                    NEIGHBOR_NSAMPLE: -1
                    POST_MLPS: [ 32, 32 ]
                GROUP_CFG_1:
                    NUM_LOCAL_VOXEL: [ 3, 3, 3 ]
                    MAX_NEIGHBOR_DISTANCE: 0.4
                    NEIGHBOR_NSAMPLE: -1
                    POST_MLPS: [ 32, 32 ]

            x_conv3:
                DOWNSAMPLE_FACTOR: 4
                INPUT_CHANNELS: 64

                NAME: VectorPoolAggregationModuleMSG
                NUM_GROUPS: 2
                LOCAL_AGGREGATION_TYPE: local_interpolation
                NUM_REDUCED_CHANNELS: 32
                NUM_CHANNELS_OF_LOCAL_AGGREGATION: 32
                MSG_POST_MLPS: [128]
                FILTER_NEIGHBOR_WITH_ROI: True
                RADIUS_OF_NEIGHBOR_WITH_ROI: 4.0

                GROUP_CFG_0:
                    NUM_LOCAL_VOXEL: [3, 3, 3]
                    MAX_NEIGHBOR_DISTANCE: 1.2
                    NEIGHBOR_NSAMPLE: -1
                    POST_MLPS: [64, 64]
                GROUP_CFG_1:
                    NUM_LOCAL_VOXEL: [ 3, 3, 3 ]
                    MAX_NEIGHBOR_DISTANCE: 2.4
                    NEIGHBOR_NSAMPLE: -1
                    POST_MLPS: [ 64, 64 ]

            x_conv4:
                DOWNSAMPLE_FACTOR: 8
                INPUT_CHANNELS: 64

                NAME: VectorPoolAggregationModuleMSG
                NUM_GROUPS: 2
                LOCAL_AGGREGATION_TYPE: local_interpolation
                NUM_REDUCED_CHANNELS: 32
                NUM_CHANNELS_OF_LOCAL_AGGREGATION: 32
                MSG_POST_MLPS: [ 128 ]
                FILTER_NEIGHBOR_WITH_ROI: True
                RADIUS_OF_NEIGHBOR_WITH_ROI: 6.4

                GROUP_CFG_0:
                    NUM_LOCAL_VOXEL: [ 3, 3, 3 ]
                    MAX_NEIGHBOR_DISTANCE: 2.4
                    NEIGHBOR_NSAMPLE: -1
                    POST_MLPS: [ 64, 64 ]
                GROUP_CFG_1:
                    NUM_LOCAL_VOXEL: [ 3, 3, 3 ]
                    MAX_NEIGHBOR_DISTANCE: 4.8
                    NEIGHBOR_NSAMPLE: -1
                    POST_MLPS: [ 64, 64 ]


    POINT_HEAD:
        NAME: PointHeadSimple
        CLS_FC: [256, 256]
        CLASS_AGNOSTIC: True
        USE_POINT_FEATURES_BEFORE_FUSION: True
        TARGET_CONFIG:
            GT_EXTRA_WIDTH: [0.2, 0.2, 0.2]
        LOSS_CONFIG:
            LOSS_REG: smooth-l1
            LOSS_WEIGHTS: {
                'point_cls_weight': 1.0,
            }

    ROI_HEAD:
        NAME: PVRCNNHead
        CLASS_AGNOSTIC: True

        SHARED_FC: [256, 256]
        CLS_FC: [256, 256]
        REG_FC: [256, 256]
        DP_RATIO: 0.3

        NMS_CONFIG:
            TRAIN:
                NMS_TYPE: nms_gpu
                MULTI_CLASSES_NMS: False
                NMS_PRE_MAXSIZE: 9000
                NMS_POST_MAXSIZE: 512
                NMS_THRESH: 0.8
            TEST:
                NMS_TYPE: nms_gpu
                MULTI_CLASSES_NMS: False
                NMS_PRE_MAXSIZE: 1024
                NMS_POST_MAXSIZE: 100
                NMS_THRESH: 0.7
                SCORE_THRESH: 0.1

#                NMS_PRE_MAXSIZE: 4096
#                NMS_POST_MAXSIZE: 500
#                NMS_THRESH: 0.85


        ROI_GRID_POOL:
            GRID_SIZE: 6

            NAME: VectorPoolAggregationModuleMSG
            NUM_GROUPS: 2
            LOCAL_AGGREGATION_TYPE: voxel_random_choice
            NUM_REDUCED_CHANNELS: 30
            NUM_CHANNELS_OF_LOCAL_AGGREGATION: 32
            MSG_POST_MLPS: [ 128 ]

            GROUP_CFG_0:
                NUM_LOCAL_VOXEL: [ 3, 3, 3 ]
                MAX_NEIGHBOR_DISTANCE: 0.8
                NEIGHBOR_NSAMPLE: 32
                POST_MLPS: [ 64, 64 ]
            GROUP_CFG_1:
                NUM_LOCAL_VOXEL: [ 3, 3, 3 ]
                MAX_NEIGHBOR_DISTANCE: 1.6
                NEIGHBOR_NSAMPLE: 32
                POST_MLPS: [ 64, 64 ]

        TARGET_CONFIG:
            BOX_CODER: ResidualCoder
            ROI_PER_IMAGE: 128
            FG_RATIO: 0.5

            SAMPLE_ROI_BY_EACH_CLASS: True
            CLS_SCORE_TYPE: roi_iou

            CLS_FG_THRESH: 0.75
            CLS_BG_THRESH: 0.25
            CLS_BG_THRESH_LO: 0.1
            HARD_BG_RATIO: 0.8

            REG_FG_THRESH: 0.55

        LOSS_CONFIG:
            CLS_LOSS: BinaryCrossEntropy
            REG_LOSS: smooth-l1
            CORNER_LOSS_REGULARIZATION: True
            LOSS_WEIGHTS: {
                'rcnn_cls_weight': 1.0,
                'rcnn_reg_weight': 1.0,
                'rcnn_corner_weight': 1.0,
                'code_weights': [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
            }

    POST_PROCESSING:
        RECALL_THRESH_LIST: [0.3, 0.5, 0.7]
        SCORE_THRESH: 0.1
        OUTPUT_RAW_SCORE: False

        EVAL_METRIC: kitti

        NMS_CONFIG:
            MULTI_CLASSES_NMS: False
            NMS_TYPE: nms_gpu
            NMS_THRESH: 0.2
            NMS_PRE_MAXSIZE: 4096
            NMS_POST_MAXSIZE: 500


OPTIMIZATION:
    BATCH_SIZE_PER_GPU: 2
    NUM_EPOCHS: 20

    OPTIMIZER: adam_onecycle
    LR: 0.01
    WEIGHT_DECAY: 0.001
    MOMENTUM: 0.9

    MOMS: [0.95, 0.85]
    PCT_START: 0.4
    DIV_FACTOR: 10
    DECAY_STEP_LIST: [35, 45]
    LR_DECAY: 0.1
    LR_CLIP: 0.0000001

    LR_WARMUP: False
    WARMUP_EPOCH: 1

    GRAD_NORM_CLIP: 10
```

**Comment by TimoRST** [comment]
I just found that you provide the possibility to download the whole folders of pretrained networks with their config files.
But this still produces the same error for me.

**Comment by darrenjkt** [comment]
What point cloud range did you specify? It should be kept the same as custom_dataset_da and nuscenes_dataset_da where it is POINT_CLOUD_RANGE: [-75.2,-75.2,-2,75.2,75.2,4]. 

You shouldn't be changing the voxel size I provided because that'll cause the detector to fail. Changing the voxel size is akin to changing the world representation for the detector, which causes it to not recognise anything anymore. Hence why it detects no objects. 

For your second question, yes the detectors are only trained on x,y,z, timestamp and ignores all other lidar channels. This was to give it as much compatibility with various lidar types. You can use whatever units for the timestamp, we just use sorted() to ensure they are in the correct temporal sequence.

**Comment by TimoRST** [comment]
Thank you very much for your help, the point cloud range was actually the point!
